[serve]
# The address to serve on.
address = "127.0.0.1"
# The port to serve on.
port = 8080
# The path to serve at.
path = "/"

[watch]
ignore = ["./dist/tailwind.css"]

[build]
target = "index.html"