[serve]
address = "127.0.0.1"
port = 8080
path = "/"

[watch]
watch = ["styles", "src"]

[build]
target = "index.html"

[[hooks]]
stage = "pre_build"
command = "cmd"
command_arguments = ["/C", "tailwindcss", "-i", "./styles/tailwind.css", "-o", "./dist/tailwind.css"]