[serve]
address = "127.0.0.1"
port = 8080
path = "/"

[watch]
watch = ["styles", "src"]

[build]
target = "index.html"

[[hooks]]
stage = "pre_build"
command = "sh"
command_arguments = ["-c", "NPX_CMD=$([ \"$OSTYPE\" = \"msys\" ] && echo npx.cmd || echo npx) && $NPX_CMD tailwindcss -i ./styles/tailwind.css -o ./dist/tailwind.css"]