name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown

      - name: Install trunk
        uses: jetli/trunk-action@v0.4.0
        with:
          version: 'latest'

      - name: Install tailwindcss
        run: npm install -D tailwindcss

      - name: Build tailwindcss
        run: npx tailwindcss -i ./styles/tailwind.css -o ./dist/tailwind.css

      - name: Build
        run: |
          trunk build --release

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist